application:
  id: querydsl-tutorials
  version: 1.0

spring:
  profiles:
    active: local
  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false # Open Session in View

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password:
    driver-class-name: org.h2.Driver

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace


server:
  port: 8080