application:
  id: querydsl-tutorials
  version: 1.0

spring:
  profiles:
    active: local
  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false # Open Session in View

  datasource:
    url: jdbc:mysql://192.168.0.83:33307/audience?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace


server:
  port: 8080